### ISSUE TITLE
Design Reflection

### ISSUE THREAD

**Issue by thompson-tyler** [thompson-tyler/canjam#10]
A reflection on your design. What was the best decision that you made? What would you do differently next time?

**Comment by CeceliaCrumlish** [comment]
I think we should separate this into the two different reflections for the separate parts of the design.

**Comment by CeceliaCrumlish** [comment]
## Design Reflection 

### Pygame Module (Cece and Roger)

To be honest this module went through a lot of changes from the initial design. As we began to work more with pygame. 

**One thing I feel particularly proud of is:** the inter-game process communication and getting everything to work in terms of updating the board visually with inbound sounds and sending outbound sounds to the correct modules. Additionally, having the game module abstracted from the process of joining a room and talking to other players was really helpful in getting everything to connect seamlessly, once the Peer-Peer portion was completed. 

**One thing I wish I would have done differently though was to do more reading up on multiprocessing vs. multithreading:** 

Initially I (Cece) thought it would be more beneficial and faster to use multiple processes with pygame as I thought it would allow for actual concurrency with the audio driver. But as it turns out inter-process communication is very slow and all the message passing and note playing on each process I was doing in that version was being hindered by how slow over the network communication was. 

**If we had had more time:** I think we would have experimented with different concurrent solutions to the displaying multiple sounds at once problem we had. However we were so spread-thin with getting the pyfluidsynth and pygame to work, that we ran out of time, and didn't get to that part.

**Comment by thompson-tyler** [comment]
Added to main
